# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Attack.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 375)
        MainWindow.setMinimumSize(QtCore.QSize(535, 375))
        MainWindow.setMaximumSize(QtCore.QSize(535, 375))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 320, 501, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 511, 301))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 51))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.tb_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.tb_comboBox.setGeometry(QtCore.QRect(350, 20, 111, 22))
        self.tb_comboBox.setObjectName("tb_comboBox")
        self.tb_comboBox.addItem("")
        self.login_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.login_pushButton.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.login_pushButton.setObjectName("login_pushButton")
        self.db_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.db_comboBox.setGeometry(QtCore.QRect(180, 20, 111, 20))
        self.db_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.db_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.db_comboBox.setObjectName("db_comboBox")
        self.db_comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(180, 0, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(350, 0, 51, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 70, 121, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.attack_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.attack_pushButton.setGeometry(QtCore.QRect(23, 180, 75, 23))
        self.attack_pushButton.setObjectName("attack_pushButton")
        self.delAttack_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.delAttack_radioButton.setGeometry(QtCore.QRect(23, 30, 71, 16))
        self.delAttack_radioButton.setObjectName("delAttack_radioButton")
        self.updAttac_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.updAttac_radioButton.setGeometry(QtCore.QRect(23, 80, 71, 16))
        self.updAttac_radioButton.setObjectName("updAttac_radioButton")
        self.algoAttack_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.algoAttack_radioButton.setGeometry(QtCore.QRect(23, 130, 71, 16))
        self.algoAttack_radioButton.setObjectName("algoAttack_radioButton")
        self.attrNum_widget = QtWidgets.QWidget(self.groupBox_3)
        self.attrNum_widget.setGeometry(QtCore.QRect(120, 20, 71, 41))
        self.attrNum_widget.setObjectName("attrNum_widget")
        self.lsb_widget = QtWidgets.QWidget(self.groupBox_3)
        self.lsb_widget.setGeometry(QtCore.QRect(120, 80, 91, 41))
        self.lsb_widget.setObjectName("lsb_widget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 351, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 26, 71, 16))
        self.label_9.setObjectName("label_9")
        self.scale_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.scale_lineEdit.setGeometry(QtCore.QRect(100, 24, 51, 20))
        self.scale_lineEdit.setObjectName("scale_lineEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(190, 26, 81, 16))
        self.label_10.setObjectName("label_10")
        self.lsb_lineEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.lsb_lineEdit.setGeometry(QtCore.QRect(270, 23, 61, 22))
        self.lsb_lineEdit.setMaximum(64)
        self.lsb_lineEdit.setProperty("value", 1)
        self.lsb_lineEdit.setObjectName("lsb_lineEdit")
        self.right_listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.right_listWidget.setGeometry(QtCore.QRect(220, 80, 111, 141))
        self.right_listWidget.setDragEnabled(True)
        self.right_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.right_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.right_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.right_listWidget.setSelectionRectVisible(True)
        self.right_listWidget.setObjectName("right_listWidget")
        self.left_listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.left_listWidget.setGeometry(QtCore.QRect(20, 80, 111, 141))
        self.left_listWidget.setDragEnabled(True)
        self.left_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.left_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.left_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.left_listWidget.setSelectionRectVisible(True)
        self.left_listWidget.setObjectName("left_listWidget")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(220, 60, 111, 16))
        self.label_12.setObjectName("label_12")
        self.delAddr_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.delAddr_pushButton.setGeometry(QtCore.QRect(150, 160, 51, 41))
        self.delAddr_pushButton.setObjectName("delAddr_pushButton")
        self.addAttr_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addAttr_pushButton.setGeometry(QtCore.QRect(150, 100, 51, 41))
        self.addAttr_pushButton.setObjectName("addAttr_pushButton")
        self.widget.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.login_pushButton, self.db_comboBox)
        MainWindow.setTabOrder(self.db_comboBox, self.tb_comboBox)
        MainWindow.setTabOrder(self.tb_comboBox, self.delAttack_radioButton)
        MainWindow.setTabOrder(self.delAttack_radioButton, self.updAttac_radioButton)
        MainWindow.setTabOrder(self.updAttac_radioButton, self.algoAttack_radioButton)
        MainWindow.setTabOrder(self.algoAttack_radioButton, self.attack_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "水印攻击程序"))
        self.groupBox.setTitle(_translate("MainWindow", "选择与连接"))
        self.tb_comboBox.setItemText(0, _translate("MainWindow", "请先选择数据库"))
        self.login_pushButton.setToolTip(_translate("MainWindow", "点击登陆MySQL"))
        self.login_pushButton.setText(_translate("MainWindow", "登录MySQL"))
        self.db_comboBox.setItemText(0, _translate("MainWindow", "请先连接MySQL"))
        self.label.setText(_translate("MainWindow", "数据库"))
        self.label_2.setText(_translate("MainWindow", "数据表"))
        self.groupBox_3.setTitle(_translate("MainWindow", "水印攻击"))
        self.attack_pushButton.setText(_translate("MainWindow", "开始攻击"))
        self.delAttack_radioButton.setToolTip(_translate("MainWindow", "随机删除元组"))
        self.delAttack_radioButton.setText(_translate("MainWindow", "删除攻击"))
        self.updAttac_radioButton.setToolTip(_translate("MainWindow", "对元组全部属性的所有不重要比特位随机替换"))
        self.updAttac_radioButton.setText(_translate("MainWindow", "更新攻击"))
        self.algoAttack_radioButton.setToolTip(_translate("MainWindow", "利用水印算法进行攻击(随机生成密钥)"))
        self.algoAttack_radioButton.setText(_translate("MainWindow", "算法攻击"))
        self.groupBox_2.setTitle(_translate("MainWindow", "参数设置"))
        self.label_9.setText(_translate("MainWindow", "攻击比例：1/"))
        self.label_10.setText(_translate("MainWindow", "不重要比特数："))
        self.label_11.setText(_translate("MainWindow", "添加水印的属性"))
        self.label_12.setText(_translate("MainWindow", "不添加水印的属性"))
        self.delAddr_pushButton.setText(_translate("MainWindow", "移除\n"
                                                                 ">>>"))
        self.addAttr_pushButton.setText(_translate("MainWindow", "添加\n"
                                                                 "<<<"))
