# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Attack.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 289)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 230, 411, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 421, 211))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 141, 181))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.tb_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.tb_comboBox.setGeometry(QtCore.QRect(10, 140, 111, 22))
        self.tb_comboBox.setObjectName("tb_comboBox")
        self.tb_comboBox.addItem("")
        self.login_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.login_pushButton.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.login_pushButton.setObjectName("login_pushButton")
        self.db_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.db_comboBox.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.db_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.db_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.db_comboBox.setObjectName("db_comboBox")
        self.db_comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(15, 60, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(15, 120, 51, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 20, 251, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.attack_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.attack_pushButton.setGeometry(QtCore.QRect(160, 136, 75, 23))
        self.attack_pushButton.setObjectName("attack_pushButton")
        self.delAttack_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.delAttack_radioButton.setGeometry(QtCore.QRect(20, 30, 89, 16))
        self.delAttack_radioButton.setObjectName("delAttack_radioButton")
        self.updAttac_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.updAttac_radioButton.setGeometry(QtCore.QRect(20, 64, 89, 16))
        self.updAttac_radioButton.setObjectName("updAttac_radioButton")
        self.algoAttack_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.algoAttack_radioButton.setGeometry(QtCore.QRect(20, 100, 89, 16))
        self.algoAttack_radioButton.setObjectName("algoAttack_radioButton")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 61, 16))
        self.label_6.setObjectName("label_6")
        self.scale_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.scale_lineEdit.setGeometry(QtCore.QRect(98, 138, 41, 20))
        self.scale_lineEdit.setObjectName("scale_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(79, 140, 16, 16))
        self.label_3.setObjectName("label_3")
        self.attrNum_widget = QtWidgets.QWidget(self.groupBox_3)
        self.attrNum_widget.setGeometry(QtCore.QRect(120, 20, 71, 41))
        self.attrNum_widget.setObjectName("attrNum_widget")
        self.label_7 = QtWidgets.QLabel(self.attrNum_widget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 61, 16))
        self.label_7.setObjectName("label_7")
        self.attrNum_lineEdit = QtWidgets.QLineEdit(self.attrNum_widget)
        self.attrNum_lineEdit.setGeometry(QtCore.QRect(0, 20, 61, 20))
        self.attrNum_lineEdit.setObjectName("attrNum_lineEdit")
        self.lsb_widget = QtWidgets.QWidget(self.groupBox_3)
        self.lsb_widget.setGeometry(QtCore.QRect(120, 80, 91, 41))
        self.lsb_widget.setObjectName("lsb_widget")
        self.label_8 = QtWidgets.QLabel(self.lsb_widget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lsb_lineEdit = QtWidgets.QLineEdit(self.lsb_widget)
        self.lsb_lineEdit.setGeometry(QtCore.QRect(0, 20, 61, 20))
        self.lsb_lineEdit.setObjectName("lsb_lineEdit")
        self.widget.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.login_pushButton, self.db_comboBox)
        MainWindow.setTabOrder(self.db_comboBox, self.tb_comboBox)
        MainWindow.setTabOrder(self.tb_comboBox, self.delAttack_radioButton)
        MainWindow.setTabOrder(self.delAttack_radioButton, self.updAttac_radioButton)
        MainWindow.setTabOrder(self.updAttac_radioButton, self.algoAttack_radioButton)
        MainWindow.setTabOrder(self.algoAttack_radioButton, self.attrNum_lineEdit)
        MainWindow.setTabOrder(self.attrNum_lineEdit, self.lsb_lineEdit)
        MainWindow.setTabOrder(self.lsb_lineEdit, self.scale_lineEdit)
        MainWindow.setTabOrder(self.scale_lineEdit, self.attack_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "水印攻击程序"))
        self.groupBox.setTitle(_translate("MainWindow", "选择与连接"))
        self.tb_comboBox.setItemText(0, _translate("MainWindow", "请先选择数据库"))
        self.login_pushButton.setToolTip(_translate("MainWindow", "点击登陆MySQL"))
        self.login_pushButton.setText(_translate("MainWindow", "登录MySQL"))
        self.db_comboBox.setItemText(0, _translate("MainWindow", "请先连接MySQL"))
        self.label.setText(_translate("MainWindow", "数据库"))
        self.label_2.setText(_translate("MainWindow", "数据表"))
        self.groupBox_3.setTitle(_translate("MainWindow", "水印攻击"))
        self.attack_pushButton.setText(_translate("MainWindow", "开始攻击"))
        self.delAttack_radioButton.setToolTip(_translate("MainWindow", "随机删除元组"))
        self.delAttack_radioButton.setText(_translate("MainWindow", "删除攻击"))
        self.updAttac_radioButton.setToolTip(_translate("MainWindow", "对元组全部属性的所有不重要比特位随机替换"))
        self.updAttac_radioButton.setText(_translate("MainWindow", "更新攻击"))
        self.algoAttack_radioButton.setToolTip(_translate("MainWindow", "利用水印算法进行攻击(随机生成密钥)"))
        self.algoAttack_radioButton.setText(_translate("MainWindow", "算法攻击"))
        self.label_6.setText(_translate("MainWindow", "攻击比例："))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">1/</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "属性个数："))
        self.label_8.setText(_translate("MainWindow", "不重要比特数："))
